import { lazy } from "react";
import Logo from "../Components/logo/Logo";

export const mainRoutes = [
 {
  name: <Logo />,
  path: "/",
  component: lazy(() => import("../pages/HomePage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Products",
  path: "/products",
  component: lazy(() => import("../pages/ProductsPage")),
  exact: false,
  isRestricted: true,
  isPrivate: false,
},
{
 name: "Accessories",
 path: "/accessories",
 component: "Accessories",
 exact: false,
 isRestricted: true,
 isPrivate: false,
},
{
 name: "Contacts",
 path: "/contacts",
 component: "Contacts",
 exact: false,
 isRestricted: true,
 isPrivate: false,
},
{
 name: "Cart",
 path: "/cart",
 component: lazy(() => import("../pages/CartPage")),
 exact: true,
 isRestricted: true,
 isPrivate: false,
 cartLength:null,
},
 {
  name: "Service",
  path: "/service",
  component: lazy(() => import("../pages/ServicePage")),
  exact: false,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Administration",
  path: "/admin",
  component: lazy(() => import("../pages/AdminPage")),
  exact: true,
  isRestricted: false,
  isPrivate: false,
 },
 {
  name: "Registration",
  path: "/registration",
  component: lazy(() => import("../pages/AuthPage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Login",
  path: "/login",
  component: lazy(() => import("../pages/AuthPage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
];
