import { lazy } from "react";

export const mainRoutes = [
 {
  name: "Home",
  path: "/",
  component: lazy(() => import("../pages/HomePage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Products",
  path: "/products",
  component: lazy(() => import("../pages/ProductsPage")),
  exact: false,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Mining",
  path: "/mining",
  component: lazy(() => import("../pages/MiningPage")),
  exact: false,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Cart",
  path: "/cart",
  component: lazy(() => import("../pages/CartPage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Administration",
  path: "/admin",
  component: lazy(() => import("../pages/AdminPage")),
  exact: true,
  isRestricted: false,
  isPrivate: false,
 },
 {
  name: "Registration",
  path: "/registration",
  component: lazy(() => import("../pages/AuthPage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
 {
  name: "Login",
  path: "/login",
  component: lazy(() => import("../pages/AuthPage")),
  exact: true,
  isRestricted: true,
  isPrivate: false,
 },
];
